<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <Title></Title>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageProjectUrl></PackageProjectUrl>
  </PropertyGroup>

</Project>
